//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFlow
{
    public partial class Default
    {

        /// <summary>
        /// control alertContainer.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertContainer;

        /// <summary>
        /// control lblTotalUsuarios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalUsuarios;

        /// <summary>
        /// control lblTotalOrdenes.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalOrdenes;

        /// <summary>
        /// control lblTotalServicios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalServicios;

        /// <summary>
        /// control lblTotalVentas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalVentas;
    }
}
