//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFlow
{
    public partial class MasterPage
    {

        /// <summary>
        /// control form1.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// control head.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        /// <summary>
        /// control ContentPlaceHolder1.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
