//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFlow
{
    public partial class Ordenes
    {

        /// <summary>
        /// control alertContainer.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertContainer;

        /// <summary>
        /// control ddlUsuarios.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlUsuarios;

        /// <summary>
        /// control txtTotal.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTotal;

        /// <summary>
        /// control btnGuardar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>
        /// control btnLimpiar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>
        /// control gvOrdenes.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOrdenes;
    }
}

