//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFlow
{
    public partial class Usuarios
    {

        /// <summary>
        /// control alertContainer.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertContainer;

        /// <summary>
        /// control txtNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>
        /// control txtEmail.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// control txtClave.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClave;

        /// <summary>
        /// control btnGuardar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>
        /// control btnLimpiar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>
        /// control gvUsuarios.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvUsuarios;
    }
}
